### ISSUE TITLE
arm32 or arm64?

### ISSUE THREAD

**Issue by nicowu07** [talos-vulndev/afl-dyninst#13]
Hi, does it support arm?

**Comment by vanhauser-thc** [comment]
that depends on Dyninst.
Dyninst 9 does not support ARM, Dyninst 10 supports aarch64 though I havent tested t. There is an experimental arm32 version in dyninst 10, but not sure its publicly accessible or even working.

**Comment by nicowu07** [comment]
Oh I see! Thanks for your quick reply.

**Comment by kevinsungdelta** [comment]
Hi i face a problem while using this on arm64(aarch64) target.
The error message: 
```
$ afl-dyninst -i ./testARM  -o ArmDy
afl-dyninst (c) 2017-2021 by Aleksandar Nikolic and Marc Heuse [https://github.com/vanhauser-thc/afl-dyninst] Apache 2.0 License
Inserting init callback.
Instrumenting module: testARM
Skipping library: libAflDyninst.so
Saving the instrumented binary to ArmDy ...
Unhandled jump conversion case: opcode is 0x40
afl-dyninst: /home/kevin/dyninst/dyninstAPI/src/codegen-x86.C:189: bool convert_to_rel32(const unsigned char*&, unsigned char*&): Assertion `0 && "Unhandled jump conversion case!"' failed.
Aborted
```
I am using dyninst10. 
It seems that afl-dyninst can't recognize if my target binary is x86 or arm.
So how can I config it?
