### ISSUE TITLE
broken build

### ISSUE THREAD

**Issue by ghost** [talos-vulndev/afl-dyninst#8]
Doesn't build anymore after one of the last changes. Basically afl-dyninst.cpp now includes dyninstversion.h (line 19), which is not in the src tree.

**Comment by vanhauser-thc** [comment]
you need to clone dyninst, compile and install it, then it is created.
it is very important not to use the last release version but using the current repository state.

**Comment by ghost** [comment]
Ok, I always used the latest dyninst release (9.3.2). Using the master branch fixes it indeed. Thank you.

**Comment by vanhauser-thc** [comment]
with the current dyninst repository state you do not need the -f fix option anymore. (although afl-dyninst still tells you so as the version counter has not been increased yet)
